services:
    mongo1:
        image: mongo
        hostname: mongo1
        container_name: mongo1
        ports:
            - 27017:27017
        # volumes:
        # - mongo1-data:/data/db
        entrypoint: ["mongod", "--replSet", "mongo-cluster-replicaset", "--bind_ip_all", "--port", "27017"] # "--bind_ip", "localhost,mongo1"
    mongo2:
        image: mongo
        hostname: mongo2
        container_name: mongo2
        ports:
            - 27018:27018
        # volumes:
        # - mongo2-data:/data/db
        entrypoint: ["mongod", "--replSet", "mongo-cluster-replicaset", "--bind_ip_all", "--port", "27018"] # "--bind_ip", "localhost,mongo2"
    mongo3:
        image: mongo
        hostname: mongo3
        container_name: mongo3
        ports:
            - 27019:27019
        # volumes:
        # - mongo3-data:/data/db
        entrypoint: ["mongod", "--replSet", "mongo-cluster-replicaset", "--bind_ip_all", "--port", "27019"] # "--bind_ip", "localhost,mongo3"
    # mongo4:
    #     image: mongo
    #     hostname: mongo4
    #     container_name: mongo4
    #     ports:
    #         - 27020:27020
    #     # volumes:
    #     # - mongo3-data:/data/db
    #     entrypoint: ["mongod", "--replSet", "mongo-cluster-replicaset", "--bind_ip_all", "--port", "27020"] # "--bind_ip", "localhost,mongo3"
    mongosetup:
        image: mongo
        depends_on:
            - mongo1
            - mongo2
            - mongo3
        volumes:
            - ./scripts:/scripts
        restart: "no"
        entrypoint: ["bash", "/scripts/mongo_setup.sh"]
# volumes:
#   mongo1-data:
#   mongo2-data:
#   mongo3-data:
